In [2]:
pip install rasterio

Note: you may need to restart the kernel to use updated packages.


In [3]:
import rasterio

In [4]:
dataset = rasterio.open("C:/Users/173330/OneDrive\Documents/JupyterNotebooks/open-geo-tutorial-master/open-geo-tutorial-master/data/RGB.byte.tif")

In [5]:
dataset.name

'C:/Users/173330/OneDrive/Documents/JupyterNotebooks/open-geo-tutorial-master/open-geo-tutorial-master/data/RGB.byte.tif'

In [6]:
dataset.mode

'r'

In [7]:
dataset.closed

False

In [8]:
dataset.count

3

In [9]:
dataset.width

791

In [10]:
dataset.height

718

In [11]:
{i: dtype for i, dtype in zip(dataset.indexes, dataset.dtypes)}

{1: 'uint8', 2: 'uint8', 3: 'uint8'}

In [12]:
dataset.bounds

BoundingBox(left=101985.0, bottom=2611485.0, right=339315.0, top=2826915.0)

In [13]:
dataset.transform

Affine(300.0379266750948, 0.0, 101985.0,
       0.0, -300.041782729805, 2826915.0)

In [14]:
dataset.transform * (0,0)

(101985.0, 2826915.0)

In [15]:
dataset.transform * (dataset.width, dataset.height)

(339315.0, 2611485.0)

In [16]:
dataset.crs

CRS.from_wkt('PROJCS["UTM Zone 18, Northern Hemisphere",GEOGCS["Unknown datum based upon the WGS 84 ellipsoid",DATUM["Not_specified_based_on_WGS_84_spheroid",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-75],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]')

In [17]:
dataset.indexes

(1, 2, 3)

In [18]:
band1 = dataset.read(1)

In [19]:
band2 = dataset.read(2)

In [20]:
band3 = dataset.read(3)

In [21]:
band1, band2, band3

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8))

In [24]:
band1[dataset.height // 2, dataset.width // 2]

18

In [25]:
band2[dataset.height // 2, dataset.width // 2]

25

In [26]:
band3[dataset.height // 2, dataset.width // 2]

14

In [29]:
x, y = (dataset.bounds.left + 100000, dataset.bounds.top - 50000)

In [30]:
row, col = dataset.index(x, y)

In [31]:
row, col

(166, 333)

In [33]:
band1[row, col], band2[row, col], band3[row, col]

(12, 41, 34)

In [34]:
dataset.xy(dataset.height // 2, dataset.width // 2)

(220650.0, 2719049.9791086353)

In [35]:
import numpy as np

In [36]:
x = np.linspace(-4.0, 4.0, 240)

In [37]:
y = np.linspace(-3.0, 3.0, 180)

In [38]:
X, Y = np.meshgrid(x, y)

In [39]:
Z1 = np.exp(-2 * np.log(2) * ((X - 0.5) ** 2 + (Y - 0.5) ** 2) / 1 ** 2)

In [40]:
Z2 = np.exp(-3 * np.log(2) * ((X + 0.5) ** 2 + (Y + 0.5) ** 2) / 2.5 ** 2)

In [41]:
Z = 10.0 * (Z2 - Z1)

In [42]:
from rasterio.transform import Affine
res = (x[-1] - x[0]) / 240.0
transform = Affine.translation(x[0] - res / 2, y[0] - res / 2) * Affine.scale(res, res)
transform

Affine(0.03333333333333333, 0.0, -4.016666666666667,
       0.0, 0.03333333333333333, -3.0166666666666666)

In [47]:
new_dataset = rasterio.open("C:/Users/173330/OneDrive\Documents/JupyterNotebooks/open-geo-tutorial-master/open-geo-tutorial-master/data/RGB.byte.tif")

In [49]:
new_dataset.width

791

In [50]:
new_dataset.close()

In [ ]:
#color

In [53]:
import rasterio
src = rasterio.open("C:/Users/173330/OneDrive\Documents/JupyterNotebooks/open-geo-tutorial-master/open-geo-tutorial-master/data/RGB.byte.tif")
src.colorinterp[0]

<ColorInterp.red: 3>

In [54]:
profile = src.profile

In [55]:
profile['photometric'] = "RGB"

In [56]:
with rasterio.open("C:/Users/173330/OneDrive\Documents/JupyterNotebooks/open-geo-tutorial-master/open-geo-tutorial-master/data/RGB.byte.tif", 'w', **profile) as dst:
    dst.write(src.read())

CPLE_AppDefinedError: Deleting C:/Users/173330/OneDrive/Documents/JupyterNotebooks/open-geo-tutorial-master/open-geo-tutorial-master/data/RGB.byte.tif failed: Permission denied